# Generated by Django 3.2.6 on 2021-08-31 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('visivel', models.BooleanField(default=True)),
            ],
        ),
    ]
