# Generated by Django 3.2.6 on 2021-08-31 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1)),
                ('modelo', models.CharField(blank=True, max_length=200)),
                ('ano_veiculo', models.IntegerField()),
                ('cor', models.CharField(blank=True, max_length=200)),
                ('placa', models.CharField(max_length=10)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('visivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('telefone', models.IntegerField()),
                ('email', models.CharField(max_length=500)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='garagem.veiculo')),
            ],
        ),
    ]
