# Generated by Django 3.2.6 on 2021-08-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('M', 'Moto'), ('C', 'Carro')], max_length=1),
        ),
    ]
