# Generated by Django 3.2.6 on 2021-09-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_alter_veiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagem',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='telefone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='garagem',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garagem.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1),
        ),
    ]
