# Generated by Django 3.2.6 on 2021-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_auto_20210901_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('M', 'Moto'), ('C', 'Carro')], max_length=1),
        ),
    ]
